# Generated by Django 4.2.1 on 2023-08-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('Trainer_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
